# GitHub Secret Scanning Configuration
# https://docs.github.com/en/code-security/secret-scanning

# Custom patterns to detect (in addition to GitHub's built-in patterns)
# Note: GitHub's built-in patterns already detect OpenAI API keys

paths-ignore:
  # Don't scan these paths for secrets
  - "docs/**"
  - "*.md"
  - "examples/**"  # Examples may have placeholder keys
